### ISSUE TITLE
level ups do not work

### ISSUE THREAD

**Issue by nerdfarfmer69** [phi-fell/carefree_leveling#2]
every time i get a skill increase or every time i level up it displays some error talking about nil factor.

When i level up my stats don't change at all regardless of the skills i raised before.

**Comment by phi-fell** [comment]
So, the nil error is definitely why you aren't getting changes.  Are you using the right version of OpenMW? On the main menu, it'll have your OpenMW version in the bottom right, could you check that?

**Comment by phi-fell** [comment]
Closing this for now since I can't replicate it on OpenMW 0.48 RC 4, but I get a similar (identical?) error on old OpenMW versions.  If anyone can confirm encountering this issue on OpenMW 0.48+, feel free to re-open.
