### ISSUE TITLE
LICENSE ?

### ISSUE THREAD

**Issue by vikdotdev** [phi-fell/carefree_leveling#4]
Hey, thanks again for the mod. I wanted to tweak it to make leveling and attribute acquisition slower and ended up changing _a lot_ of stuff and published it in a [repository](https://github.com/vikdotdev/openmw-steady-leveling). 

Since your repository does not have any license and my code is heavily based on yours I just want to make sure you're okay with me copying some of your code :smile_cat:.

Just put a thumbs up or add a license if you want to let me know. Thanks.

**Comment by phi-fell** [comment]
Oh yeah, you can do whatever you like with this.  A comment with a link to this repo is appreciated but not required.  I'll add a license file real quick
