### ISSUE TITLE
Attribute stuck at 95

### ISSUE THREAD

**Issue by KalCBN** [phi-fell/carefree_leveling#5]
Whenever an attribute is leveled to 95, and you try to level up that attribute in the level up screen, the attribute will not level up beyond 95. It will be stuck at 95 regardless of if you have the skills ups required and you've selected that attribute in the level up screen.

**Comment by TECorcoran** [comment]
I'm still having this issue on a tes3mp 0.8.1 server. Attributes claim a x5 boost but they don't change after selecting them on level up, still at 95 - multiple stats across multiple characters/clients. I also double checked the player files and attribute_points_owed is 0 for those. I can include my own character file here (login info removed) if it might be helpful.

[character.json](https://github.com/user-attachments/files/21823838/character.json)

**Comment by phi-fell** [comment]
The tes3mp version is completely separate code from the main openmw version, since the two currently have different modding APIs.  The previous fix was for the standard openmw version.  I probably made the same mistake twice.
